#!/bin/sh
# Author: Louie Chen <louie23 _at_ lavabit com>
# License: GPL-3+
# Description: This script find the last used knockd one time sequence and send it to twitter
# Change one_time_sequences to fit your file
# This script works with bti for command line twitter client.
# Please setup your twitter account with your normal user first.
# The knockd is run as root, so this script su to normal username to send tweets.
# Usage: ./send-knockd-one-time-sequences-to-twitter  your_normal_username

binary=bti
one_time_sequences=/etc/knockd.sequences

if [ -z "$1" ]
then
	echo "usage: $0 username"
	exit 1
fi

username=$1

text=$(grep ^# $one_time_sequences | tail -n1 | tr -d "#")

if [ -z "$text" ]
then
	exit 1
fi

su - $username -c "echo $text | $binary"
